export const aiReports = [
  {
    id: 1,
    title: "펄어비스 - 매수",
    signalBadge: "매수신호",
    ticker: "263750",
    stockName: "펄어비스",
    generatedDate: "2026-03-12",
    generatedTime: "09:30",
    aiScore: 92,
    category: "실적 서프라이즈",
    summary: "신작 흥행 및 경영진 자사주 매수로 인한 강력한 매수 모멘텀 발생.",
    reason: "4분기 실적 호조 및 내부자 매수 포착.",
  },
  {
    id: 4,
    title: "삼성전자 - 매수",
    signalBadge: "매수신호",
    ticker: "005930",
    stockName: "삼성전자",
    generatedDate: "2026-03-12",
    generatedTime: "09:15",
    aiScore: 85,
    category: "반도체 업황 개선",
    summary: "HBM 공급망 확대 및 메모리 가격 반등 기대감.",
    reason: "메모리 업황 바닥 통과 및 AI 수요 폭증.",
  },
  {
    id: 5,
    title: "SK하이닉스 - 매수",
    signalBadge: "매수신호",
    ticker: "000660",
    stockName: "SK하이닉스",
    generatedDate: "2026-03-12",
    generatedTime: "10:05",
    aiScore: 94,
    category: "AI 반도체 주도",
    summary: "HBM3E 양산 본격화로 수익성 극대화 전망.",
    reason: "엔비디아향 공급 물량 확대 및 수율 개선.",
  },
  {
    id: 6,
    title: "현대차 - 매수",
    signalBadge: "매수신호",
    ticker: "005380",
    stockName: "현대차",
    generatedDate: "2026-03-12",
    generatedTime: "11:20",
    aiScore: 88,
    category: "주주환원 강화",
    summary: "역대급 실적 기반 배당 확대 및 자사주 소각.",
    reason: "밸류업 프로그램 수혜 및 하이브리드 판매 호조.",
  },
  {
    id: 2,
    title: "알테오젠 - 매도",
    signalBadge: "매도신호",
    ticker: "196170",
    stockName: "알테오젠",
    generatedDate: "2026-03-12",
    generatedTime: "08:45",
    aiScore: 78,
    category: "차익실현 구간",
    summary: "단기 급등에 따른 기간 조정 및 기관 매도세 포착.",
    reason: "기술적 과열 신호 발생 및 주요 지지선 이탈.",
  },
  {
    id: 7,
    title: "카카오 - 매도",
    signalBadge: "매도신호",
    ticker: "035720",
    stockName: "카카오",
    generatedDate: "2026-03-12",
    generatedTime: "13:30",
    aiScore: 65,
    category: "성장성 둔화",
    summary: "콘텐츠 부문 부진 및 광고 매출 성장세 정체.",
    reason: "영업이익 전망치 하향 및 외인 순매도 지속.",
  },
  {
    id: 8,
    title: "네이버 - 매도",
    signalBadge: "매도신호",
    ticker: "035420",
    stockName: "네이버",
    generatedDate: "2026-03-12",
    generatedTime: "14:15",
    aiScore: 72,
    category: "경쟁 심화",
    summary: "C-커머스 공세로 인한 쇼핑 부문 점유율 하향.",
    reason: "라인야후 관련 불확실성 및 기술적 하단 돌파.",
  },
  {
    id: 9,
    title: "셀트리온 - 매도",
    signalBadge: "매도신호",
    ticker: "068270",
    stockName: "셀트리온",
    generatedDate: "2026-03-12",
    generatedTime: "15:00",
    aiScore: 70,
    category: "모멘텀 부족",
    summary: "합병 이후 시너지 가시성 부족 및 신약 성과 지연.",
    reason: "PBM 등재 불확실성 및 공매도 잔고 증가.",
  },
  {
    id: 3,
    title: "에코프로비엠 - 중립",
    signalBadge: "중립신호",
    ticker: "247540",
    stockName: "에코프로비엠",
    generatedDate: "2026-03-11",
    generatedTime: "16:20",
    aiScore: 82,
    category: "업황 관망",
    summary: "전기차 수요 둔화 우려와 수주 기대감이 공존하는 구간.",
    reason: "리튬 가격 안정화 대기 및 업종 내 순환매 양상.",
  },
];
