export const stocks = [
  {
    id: 1,
    name: "펄어비스",
    code: "263750",
    currentPrice: "45,200",
    changePercent: "+4.87%",
    isPositive: true,
    characteristic: "공격적 모멘텀 · 글로벌 신작",
    upside: [
      "'붉은사막' 글로벌 출시 일정 구체화로 인한 기대감 상승",
      "중국 판호 발급 가능성 및 기존작 중국 매출 반등 여지",
      "자체 엔진 고도화를 통한 비용 절감 및 타사 라이선스 수익 기대",
    ],
    downside: [
      "신작 출시 지연 시 단기 모멘텀 소멸 및 실적 악화 우려",
      "글로벌 AAA급 게임 경쟁 심화로 인한 마케팅 비용 증가",
    ],
    rationale: [
      "26년 예상 PER 12배 수준으로 밸류에이션 매력도 높음",
      "기관 및 외국인 동시 순매수 유입 (최근 5거래일 연속)",
      "게임스컴 등 주요 글로벌 게임쇼 출품을 통한 긍정적 프리뷰 다수 확보",
    ],
  },
  {
    id: 2,
    name: "에코프로비엠",
    code: "247540",
    currentPrice: "156,000",
    changePercent: "-2.01%",
    isPositive: false,
    characteristic: "안정적 성장 · 섹터 대장주",
    upside: [
      "북미 및 유럽 시장 전기차 침투율 반등에 따른 하이니켈 양극재 수요 증가",
      "신규 수주 계약 체결 임박 및 조인트벤처(JV) 설립 가시화",
      "LFP 배터리 대비 NCM 배터리의 성능 우위 지속 증명",
    ],
    downside: [
      "리튬 등 주요 광물 가격 하락으로 인한 단기 판가 연동 수익성 악화",
      "글로벌 완성차 업체들의 전기차(전동화) 속도 조절 현상",
    ],
    rationale: [
      "고객사 다변화를 통한 매출 안정성 확보 및 27년 캐파(CAPA) 증설 계획 차질 없음",
      "최근 주가 하락으로 역발상 매수(Contrarian) 관점에서 접근 유효",
      "경쟁사 대비 원가 경쟁력 확보 및 수직 계열화 효과 본격화",
    ],
  },
  {
    id: 3,
    name: "삼성전자",
    code: "005930",
    currentPrice: "72,500",
    changePercent: "+1.25%",
    isPositive: true,
    characteristic: "반등 시그널 · HBM 공급 확대",
    upside: [
      "HBM3E 공급 본격화에 따른 D램 수익성 개선 가속화",
      "파운드리 게이트올어라운드(GAA) 공정 수율 안정화 및 대형 수주 기대",
      "AI 서버 및 온디바이스 AI 시장 확대에 따른 메모리 수요 폭증",
    ],
    downside: [
      "매크로 불확실성에 따른 글로벌 가전 및 모바일 수요 회복 지연",
      "경쟁사의 HBM 시장 선점 유지 및 수익성 격차 지속 우려",
    ],
    rationale: [
      "밸류에이션 하단 도달로 인한 하방 경직성 확보 및 저평가 매력",
      "엔비디아 퀄 테스트 통과 임박설 등 단기 강력한 모멘텀 대기",
      "주주 환원 정책 강화에 따른 배당 수익률 매력 상승",
    ],
  },
  {
    id: 4,
    name: "SK하이닉스",
    code: "000660",
    currentPrice: "185,400",
    changePercent: "+3.42%",
    isPositive: true,
    characteristic: "AI 반도체 주도주 · 실적 서프라이즈",
    upside: [
      "HBM 시장 내 절대적 지위 유지 및 High-end 제품 공급 주도",
      "AI GPU 수요 폭증에 따른 고대역폭 메모리 주문량 초과 달성",
      "낸드(NAND) 사업부 흑자 전환 및 기업용 SSD 매출 비중 확대",
    ],
    downside: [
      "반도체 사이클 정점 도달 우려에 따른 선반영 주가 조정 가능성",
      "HBM 생산 캐파 증설을 위한 대규모 설비 투자(CAPEX) 부담",
    ],
    rationale: [
      "역대 최대 실적 경신 지속 전망 및 AI 반도체 생태계 내 핵심적 위치",
      "외국인 수급 집중 현상 지속 및 목표 주가 상향 조정 리포트 다수",
      "DDR5 등 차세대 고성능 메모리 전환 가속화에 따른 ASP 상승",
    ],
  },
  {
    id: 5,
    name: "NAVER",
    code: "035420",
    currentPrice: "198,000",
    changePercent: "-0.85%",
    isPositive: false,
    characteristic: "생성형 AI '하이퍼클로바X' · 플랫폼 경쟁력",
    upside: [
      "B2B AI 솔루션 도입 본격화 및 기업용 협업 툴 수익 창출",
      "커머스 부문 광고 단가 상승 및 멤버십 혜택 확대를 통한 점유율 방어",
      "자회사 웹툰 엔터테인먼트 상장 후 지분 가치 재부각",
    ],
    downside: [
      "글로벌 빅테크(구글, 오픈AI 등)의 검색 시장 침투 가속화",
      "국내 내수 소비 위축에 따른 광고 수익 성장성 둔화 우려",
    ],
    rationale: [
      "과거 평균 밸류에이션 대비 현저한 저평가 구간 진입",
      "AI 기술 자립화를 통한 한국어 특화 서비스 시장 선점 우위",
      "안정적 현금 흐름을 기반으로 한 자사주 소각 등 주주 환원 기대",
    ],
  },
  {
    id: 6,
    name: "현대차",
    code: "005380",
    currentPrice: "245,500",
    changePercent: "+2.10%",
    isPositive: true,
    characteristic: "실적 최대치 경신 · 하이브리드 강세",
    upside: [
      "전기차 수요 둔화기 하이브리드(HEV) 차종의 압도적 수익성 증명",
      "인도 법인 상장 추진을 통한 자금 확보 및 신흥 시장 공략 가속화",
      "믹스 개선(SUV, 제네시스 비중 확대)을 통한 평균 판매 단가 상승",
    ],
    downside: [
      "글로벌 금리 인하 지연 시 자동차 할부 수요 위축 가능성",
      "미국/유럽 등 주요 시장 내 보조금 규정 변화 및 통상 압박",
    ],
    rationale: [
      "역대급 저PER(4-5배) 구간으로 밸류업 프로그램 최대 수혜주",
      "분기 배당 정례화 및 강력한 배당 성장성 확보",
      "수소 및 자율주행 등 미래 모빌리티 기술 투자 지속",
    ],
  },
  {
    id: 7,
    name: "카카오",
    code: "035720",
    currentPrice: "48,200",
    changePercent: "-1.15%",
    isPositive: false,
    characteristic: "카카오톡 기반 비즈니스 익스팬션 · 체질 개선",
    upside: [
      "톡채널 서비스 리뉴얼을 통한 광고 효율 증대 및 중소상공인 유입",
      "카카오뱅크, 카카오페이 등 주요 계열사 실적 반등 및 시너지 창출",
      "클라우드 및 미디어 콘텐츠 글로벌 수출 성과 가시화",
    ],
    downside: [
      "경영진 사법 리스크 및 지배구조 개선과 관련된 대외적 우려",
      "메신저 시장 포화에 따른 신규 사용자 유입 정체 및 경쟁 심화",
    ],
    rationale: [
      "비핵심 사업부 정리 및 본업 집중을 통한 수익 구조 효율화 진행",
      "대규모 트래픽을 활용한 AI 서비스 접목 가능성 무궁무진",
      "주가 과매도 구간 판단에 따른 저가 매수세 유입 가능성",
    ],
  },
];

export const clients = [
  {
    id: "1",
    name: "김민준",
    email: "minjun.kim@email.com",
    portfolio: "2.4억",
    memo: "AI반도체 관심 높음",
  },
  {
    id: "2",
    name: "박민수",
    email: "minsoo.park@example.com",
    portfolio: "1.8억",
  },
  {
    id: "3",
    name: "정수현",
    email: "soohyun.jung@example.com",
    portfolio: "3.1억",
  },
  {
    id: "4",
    name: "최지훈",
    email: "jihoon.choi@example.com",
    portfolio: "950만",
    memo: "바이오, 헬스케어 관심 높음",
  },
  {
    id: "5",
    name: "김나영",
    email: "nayoung.kim@example.com",
    portfolio: "1.5억",
  },
];
